CREATE TABLE IF NOT EXISTS dim_deputados(
    ID_DEPUTADO INT PRIMARY KEY,
    NOME TEXT NOT NULL UNIQUE,
    PARTIDO TEXT NOT NULL,
    ESTADO TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    NASCIMENTO DATE NOT NULL,
    ESCOLARIDADE TEXT
);

CREATE TABLE IF NOT EXISTS fact_gastos(
    ID_GASTOS SERIAL PRIMARY KEY,
    ID_DEPUTADO INT REFERENCES dim_deputados(ID_DEPUTADO),
    ANO INT NOT NULL,
    MES INT NOT NULL,
    TIPO_DESPESA TEXT NOT NULL,
    COD_DOCUMENTO TEXT NOT NULL,
    TIPO_DOCUMENTO TEXT NOT NULL,
    COD_TIPO_DOCUMENTO INT NOT NULL,
    DATA_DOCUMENTO TIMESTAMP NOT NULL,
    NUM_DOCUMENTO TEXT NOT NULL,
    VALOR_DOCUMENTO NUMERIC(10,2) NOT NULL,
    URL_DOCUMENTO TEXT NOT NULL,
    NOME_FORNECEDOR TEXT NOT NULL,
    CNPJ_FORNECEDOR TEXT NOT NULL,
    VALOR_LIQUIDO NUMERIC(10,2) NOT NULL,
    VALOR_GLOSA NUMERIC(10,2) NOT NULL,
    NUM_RESSARCIMENTO TEXT NOT NULL,
    COD_LOTE INT NOT NULL,
    PARCELA INT NOT NULL
);