IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'gastos_parlamentares')
BEGIN
    CREATE DATABASE gastos_parlamentares;
END
GO

USE gastos_parlamentares;
GO

IF NOT EXISTS(SELECT name FROM sys.tables WHERE name = 'dim_deputados')
BEGIN
    CREATE TABLE dim_deputados(
        ID_DEPUTADO INT IDENTITY(1,1) PRIMARY KEY,
        NOME VARCHAR(255) NOT NULL UNIQUE,
        PARTIDO VARCHAR(10) NOT NULL,
        ESTADO VARCHAR(2) NOT NULL,
        EMAIL VARCHAR(255) NOT NULL,
        NASCIMENTO DATE NOT NULL,
        ESCOLARIDADE VARCHAR(255)
    );
END
GO

IF NOT EXISTS(SELECT name FROM sys.tables WHERE name = 'fact_gastos')
BEGIN
    CREATE TABLE fact_gastos(
        ID_GASTOS INT IDENTITY(1,1) PRIMARY KEY,
        ID_DEPUTADO INT FOREIGN KEY REFERENCES dim_deputados(ID_DEPUTADO),
        ANO INT NOT NULL,
        MES INT NOT NULL,
        TIPO_DESPESA VARCHAR(255) NOT NULL,
        COD_DOCUMENTO VARCHAR(50) NOT NULL,
        TIPO_DOCUMENTO VARCHAR(255) NOT NULL,
        DATA_DOCUMENTO DATETIME NOT NULL,
        NUM_DOCUMENTO VARCHAR(50) NOT NULL,
        VALOR_DOCUMENTO FLOAT NOT NULL,
        URL_DOCUMENTO VARCHAR(255) NOT NULL,
        NOME_FORNECEDOR VARCHAR(255) NOT NULL,
        CNPJ_FORNECEDOR VARCHAR(255) NOT NULL,
        VALOR_LIQUIDO FLOAT NOT NULL,
        VALOR_GLOSA FLOAT NOT NULL,
        NUM_RESSARCIMENTO VARCHAR(255) NOT NULL,
        COD_LOTE INT NOT NULL,
        PARCELA INT NOT NULL
    );
END
GO